apiVersion: 1
datasources:
  - name: atf-influxdb
    uid: atf-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: atf
      defaultBucket: atf_metrics
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
